### ISSUE TITLE
Explorer question

### ISSUE THREAD

**Issue by abides** [Luracast/Restler#596]
Actually there is no serious issue but ;

When some class working as root its methods are not under the /root in Explorer, they are seperated;
$r->addAPIClass('Project\\Home','');
![root](https://user-images.githubusercontent.com/726511/40358091-d6f689ea-5dc6-11e8-9327-df6f6ccfda5a.PNG)
Is it possible to group them together in the explorer?

Best regards

**Comment by Arul-** [comment]
RC5 or RC6?

**Comment by abides** [comment]
Its RC5 but now im totally confused, upgraded to RC6 /resources call is ok but all /resources/etc  calls comes with notification;
`<br />
<b>Notice</b>:  Undefined index: url in <b>/var/www/api/vendor/restler/framework/Luracast/Restler/Resources.php</b> on line <b>228</b><br />`

Then i realize there is /explorer/swagger call added for swagger 2.0 support i guess. But it comes with warning;
`<br />
<b>Warning</b>:  explode() expects parameter 2 to be string, array given in <b>/var/www/api.3adam.net/vendor/restler/framework/Luracast/Restler/Util.php</b> on line <b>229</b><br />
<br />
<b>Warning</b>:  end() expects parameter 1 to be array, null given in <b>/var/www/api/vendor/restler/framework/Luracast/Restler/Util.php</b> on line <b>230</b><br />`

I modify Util.php line 229 to fix this warning;

`if(is_string($className)) $className = explode('\\', $className);`

Now i dont know what to do. With swagger 2.0 support using /explorer/swagger call means /resources are not necessary anymore? Should i copy Explorer 2.0 client from vendor folder to public folder? Documentation shows 1.1 related stuff.

Thanks for help.

**Comment by Arul-** [comment]
Take a look at the comments of https://github.com/Luracast/Restler/commit/9ca6dadb5f17e6dedccc3087957c8e2e25bd6cf8

Support for both Swagger 1.2 and Swagger 2 and ability to choose either or both explorers

	$r->addAPIClass('Explorer1', 'explorer'); //swagger 1.2 spec
	$r->addAPIClass('Explorer2', 'explorer2'); //swagger 2 spec

You can always add

	$r->addAPIClass('Explorer'); //for latest swagger spec (currently 2)


Simply by adding explorer class you will get the swagger api and needed html and css

Resources class is still there, to be removed in the near future

**Comment by abides** [comment]
Thank you Arul,

I made some changes on index.php;
Changed $r->addAPIClass('Resources'); to $r->addAPIClass('Explorer');
Changed Resources::$hideProtected = false; to Explorer::$hideProtected = false;

I copied client from restler/Explorer/v2/client to public and change the url in index.html to /explorer/swagger.json and its start working after i fixed the warning in Util.php.

Added validatorUrl: null in new SwaggerUi() to disable online validator (i dont want to send calls or results or anything to outside)

Now my only problem is i extend Compose and my json outputs wrapped with something else and this is not work with swagger. Im using like {status:ok, message:result}

Any way to use default Compose on Explorer only?

**Comment by abides** [comment]
Just realized some weird situation. Swagger warn me "The 'info' tag conflicts with a SwaggerClient function/property name.  Use 'client._info' or 'client.apis.info' instead of 'client.info'" because i have /info api. (I changed it to info2 then warning dissapear)

Is that means all api calls need to be in "client.apis" in explorer/swagger to avoid this kind of conflicts?

**Comment by abides** [comment]
I solve the problem just adding this to my Compose extention before my custom return;
`if($this->restler->apiMethodInfo->url=='explorer/swagger') return $result;`

Swagger warning still there. I dont know what to do about it.

Also my first question still exist after succesfully upgrade to RC6. Now its looking like this;

![root](https://user-images.githubusercontent.com/726511/40429738-12e701a6-5eac-11e8-8fc8-ca3d337a3a8b.PNG)

**Comment by Arul-** [comment]
Please try restler 5 and reopen this issue if problem persists
